spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_platform
    username: 
    password: 
  task:
    execution:
      thread-name-prefix: UserExecutor-
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 1000
        keep-alive: 60s
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1024MB
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
  mail:
    host: smtp.qq.com
    # smtp的指定端口 使用465要将protocol改为smtps
    port: 465
    username: # 你的邮箱
    password: # 密钥
    # 协议 默认就是smtp
    protocol: smtps
    # 编码格式 默认就是utf-8
    default-encoding: utf-8
    # 设置开启ssl
    properties:
      mail:
        smtp:
          from: # 你的邮箱
          ssl:
            enable: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


jwt:
  secret-key: RGa0cqPoSZlUuefLhkOdTPBLGlIn+4nSQOU9R6uTUUg=
  ttl: 43200000

leancloud:
  initialization:
    app-id: 
    app-key: 
    server-url: 
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
